/**
 * R90 Backend — Recommendation Metadata
 *
 * Static lookup tables for recommendation category, cooldown, and delivery channel.
 * Mirrors the constants defined in the engine recommendation-engine.ts.
 */

import type { RecommendationType } from "../../engine/types.js";

export const REC_CATEGORY: Record<RecommendationType, string> = {
  "REC-01": "foundation",
  "REC-02": "scheduling",
  "REC-03": "scheduling",
  "REC-04": "foundation",
  "REC-05": "scheduling",
  "REC-06": "scheduling",
  "REC-07": "environment_light",
  "REC-08": "environment_light",
  "REC-09": "environment_light",
  "REC-10": "environment_light",
  "REC-11": "environment_light",
  "REC-12": "scheduling",
  "REC-13": "anxiety_mindset",
  "REC-14": "scheduling",
  "REC-15": "anxiety_mindset",
  "REC-16": "anxiety_mindset",
  "REC-17": "scheduling",
  "REC-18": "tracking_review",
  "REC-19": "specialist",
  "REC-20": "foundation",
  "REC-21": "scheduling",
  "REC-22": "scheduling",
  "REC-23": "anxiety_mindset",
  "REC-24": "scheduling",
  "REC-25": "scheduling",
  "REC-26": "environment_light",
};

export const REC_COOLDOWN_HOURS: Record<string, number> = {
  "REC-01": 0,
  "REC-02": 12,
  "REC-03": 24,
  "REC-04": 0,
  "REC-05": 2,
  "REC-06": 24,
  "REC-07": 24,
  "REC-08": 24,
  "REC-09": 48,
  "REC-10": 72,
  "REC-11": 168,
  "REC-12": 168,
  "REC-13": 72,
  "REC-14": 72,
  "REC-15": 48,
  "REC-16": 48,
  "REC-17": 48,
  "REC-18": 168,
  "REC-19": 336,
  "REC-20": 0,
  "REC-21": 336,
  "REC-22": 48,
  "REC-23": 0,
  "REC-24": 0,
  "REC-25": 72,
  "REC-26": 0,
};

export const REC_DELIVERY_CHANNEL: Record<string, string> = {
  "REC-01": "in_app_card",
  "REC-02": "in_app_card",
  "REC-03": "push_notification",
  "REC-04": "in_app_card",
  "REC-05": "push_notification",
  "REC-06": "push_notification",
  "REC-07": "push_notification",
  "REC-08": "push_notification",
  "REC-09": "in_app_card",
  "REC-10": "in_app_card",
  "REC-11": "in_app_card",
  "REC-12": "in_app_card",
  "REC-13": "in_app_card",
  "REC-14": "weekly_review",
  "REC-15": "in_app_card",
  "REC-16": "push_notification",
  "REC-17": "in_app_card",
  "REC-18": "in_app_card",
  "REC-19": "in_app_card",
  "REC-20": "onboarding_step",
  "REC-21": "in_app_card",
  "REC-22": "in_app_card",
  "REC-23": "in_app_card",
  "REC-24": "in_app_card",
  "REC-25": "in_app_card",
  "REC-26": "in_app_card",
};
